### ISSUE TITLE
doPathsearch -  infinite loop - after 15min-30min.

### ISSUE THREAD

**Issue by DaDj** [DaDj/GTA-BTLC#2]
The game gets stuck in a do..while inside the dopathsearch function after 15min-30min of gameplay.

educated guess -> error in path-nodes.

**Comment by DaDj** [comment]
fixed

**Comment by ifarbod** [comment]
@DaDj How did you fix it?

**Comment by DaDj** [comment]
by changing the path exporter to a technically wrong format. the 'right' format fucked up the arry slighlty.

**Comment by DaDj** [comment]
--> reappearing. less frequent. infinite loop created by dopathsearch caused by copspawn functions. -.-
